# Simple Linear Regression

In [1]:
import numpy as np
import pandas as pd

In [2]:
import os
os.getcwd()

'/home/kousik/ABC_OTHERS/My_GitHub/Linear_Regression'

In [3]:
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.metrics import r2_score

In [4]:
X,y = load_diabetes(return_X_y=True)

In [5]:
X.shape

(442, 10)

In [6]:
X = X[:,0]

In [7]:
X.shape

(442,)

In [8]:
y.shape

(442,)

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

### Using Custom LR

In [10]:
class CustomLR:
    def __init__(self):
        self.m = None
        self.b = None
        
    def fit(self,X_train,y_train): 
        num = 0
        den = 0
        
        for i in range(X_train.shape[0]):
            num = num + ((X_train[i] - X_train.mean())*(y_train[i] - y_train.mean()))
            den = den + ((X_train[i] - X_train.mean())*(X_train[i] - X_train.mean()))
        
        self.m = num/den
        self.b = y_train.mean() - (self.m * X_train.mean())    
    
    def predict(self,X_test):
        return self.m * X_test + self.b

In [11]:
lr = CustomLR()

In [12]:
lr.fit(X_train,y_train)

In [13]:
lr.b

153.25920153319478

In [14]:
lr.m

331.072172004137

In [15]:
y_pred = lr.predict(X_test)

In [16]:
r2_score(y_test,y_pred)

0.008289640305771395

### Using Sklearn's Linear Regression

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [18]:
slr = LinearRegression()

In [19]:
X_train.shape

(353,)

In [20]:
X_train = X_train.reshape(-1,1)
X_test = X_test.reshape(-1,1)

In [21]:
X_train.shape

(353, 1)

In [22]:
slr.fit(X_train,y_train)

LinearRegression()

In [23]:
slr.intercept_

153.25920153319478

In [24]:
slr.coef_

array([331.072172])

In [25]:
y_pred = slr.predict(X_test)

In [26]:
r2_score(y_test,y_pred)

0.008289640305771506

# Multiple Linear Regression

In [27]:
import numpy as np
from sklearn.datasets import load_diabetes

In [28]:
load_diabetes

<function sklearn.datasets._base.load_diabetes(*, return_X_y=False, as_frame=False, scaled=True)>

In [29]:
X,y = load_diabetes(return_X_y=True)

In [30]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [31]:
X.shape

(442, 10)

In [32]:
y.shape

(442,)

In [33]:
y.shape

(442,)

### Using Sklearn's Linear Regression

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [36]:
print(X_train.shape)
print(X_test.shape)

(353, 10)
(89, 10)


In [37]:
from sklearn.linear_model import LinearRegression

In [38]:
reg = LinearRegression()

In [39]:
reg.fit(X_train,y_train)

LinearRegression()

In [40]:
y_pred = reg.predict(X_test)

In [41]:
from sklearn.metrics import r2_score

In [42]:
r2_score(y_test,y_pred)

0.4399338661568968

In [43]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [44]:
reg.intercept_

151.88331005254167

In [45]:
X_train.shape

(353, 10)

In [46]:
np.insert(X_train,0,1,axis=1).shape

(353, 11)

### Using Custom MLR

In [47]:
class CustomMLR:
    def __init__(self):
        self.intercept_ = None
        self.coef_ = None
    
    def fit(self,X_train,y_train):
        X_train = np.insert(X_train,0,1,axis=1)
        
        beta = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = beta[0]
        self.coef_ = beta[1:]
        
    def predict(self,X_test):
        y_pred = np.dot(X_test,self.coef_) + self.intercept_
        return y_pred
   

In [48]:
lr = CustomMLR()

In [49]:
lr.fit(X_train,y_train)

In [50]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [51]:
lr.intercept_

151.88331005254167

In [52]:
X_test.shape

(89, 10)

In [53]:
lr.coef_.shape

(10,)

In [57]:
#lr.predict(X_test)

In [55]:
y_pred = lr.predict(X_test)

In [56]:
r2_score(y_test,y_pred)

0.4399338661568972